%                      Cartesian Product Generator        
%
%
% The following code creates a cartesian product of the provided
% parameters. This can be used to perform a grid search on the GA
% algorithm.
%

function cartesian_product = GenerateCartesianProduct(...
                                    population_size,...
                                    generations,...
                                    crossover_probability,...
                                    mutation_probability,...
                                    SELECTION_METHOD,... 
                                    CROSSOVER_METHOD,...
                                    MUTATION_METHOD)
                                        
    % Store length of each parameter
    nRows = [...
                length(population_size),...
                length(generations),...
                length(crossover_probability),...
                length(mutation_probability),...
                length(SELECTION_METHOD),...
                length(CROSSOVER_METHOD),...
                length(MUTATION_METHOD)];

    % Create N-Dimensional grid
    [p1,p2,p3,p4,p5,p6,p7] = ndgrid(...
                1:nRows(1),...
                1:(nRows(2)),...
                1:(nRows(3)),...
                1:nRows(4),...
                1:(nRows(5)),...
                1:(nRows(6)),...
                1:nRows(7));        

    % Create the cartesian product
    cartesian_product = [...
                population_size(         p1(:), : )...
                generations(             p2(:), : )...
                crossover_probability(   p3(:), : )...
                mutation_probability(    p4(:), : )...
                SELECTION_METHOD(        p5(:), : )...
                CROSSOVER_METHOD(        p6(:), : )...
                MUTATION_METHOD(         p7(:), : )];
            
            
end
        
        
        
        